export const properties_data = [
    {
      id: "diamniadio-01",
      title: "Terrain Viabilisé à Diamniadio",
      type: "Terrain",
      image: "https://picsum.photos/1200/800?random=1",
      hint: "serviced land plot",
      price: "15 000 000 FCFA",
      area: 150,
      isNew: true,
      description: "Situé dans le pôle urbain de Diamniadio, ce terrain viabilisé de 150m² est une opportunité idéale pour construire la maison de vos rêves. Proche des infrastructures modernes, des écoles et des commerces, il offre un cadre de vie exceptionnel pour les familles et les professionnels. Le terrain est déjà raccordé aux réseaux d'eau, d'électricité et d'assainissement.",
      features: ["Proximité des transports en commun", "Zone en plein développement", "Titre foncier individuel"],
    },
    {
      id: "lac-rose-01",
      title: "Terrain Résidentiel à Lac Rose",
      type: "Terrain",
      image: "https://picsum.photos/1200/800?random=2",
      hint: "residential land",
      price: "22 000 000 FCFA",
      area: 200,
      isNew: false,
      description: "Magnifique terrain de 200m² dans un cadre paisible et naturel près du célèbre Lac Rose. Parfait pour une résidence secondaire ou un projet écotouristique. La zone est réputée pour son calme et sa beauté naturelle, offrant un échappatoire parfait à l'agitation de la ville. Le terrain est plat et prêt à construire.",
      features: ["Cadre naturel et calme", "Potentiel touristique", "Accès facile depuis Dakar"],
    },
    {
      id: "dakar-01",
      title: "Appartement T3 à Dakar",
      type: "Appartement",
      image: "https://picsum.photos/1200/800?random=3",
      hint: "modern apartment dakar",
      price: "Nous consulter",
      bedrooms: 2,
      bathrooms: 2,
      area: 100,
      isNew: false,
      description: "Spacieux et lumineux appartement de type T3 au cœur de Dakar. Il se compose de deux chambres, deux salles de bains, un grand salon et une cuisine moderne équipée. L'immeuble est sécurisé et dispose d'un ascenseur et d'un parking. Idéalement situé, vous serez à proximité de toutes les commodités : commerces, restaurants, et écoles.",
      features: ["Emplacement central", "Immeuble sécurisé 24/7", "Balcon avec vue dégagée"],
    },
    {
      id: "saly-01",
      title: "Villa 4 Chambres à Saly",
      type: "Maison",
      image: "/maison1.png",
      hint: "villa saly senegal",
      price: "Nous consulter",
      bedrooms: 4,
      bathrooms: 3,
      area: 225,
      isNew: true,
      description: "Superbe villa neuve de 4 chambres dans la station balnéaire prisée de Saly. Profitez de son jardin privé avec piscine, de sa grande terrasse et de ses finitions haut de gamme. La villa est parfaite pour une résidence principale ou un investissement locatif. La résidence est sécurisée et offre un accès facile à la plage et aux commerces.",
      features: ["Piscine privée", "Jardin paysager", "À 5 minutes de la plage"],
    },
    {
      id: "yenne-01",
      title: "Terrain d'Avenir à Yenne",
      type: "Terrain",
      image: "https://picsum.photos/1200/800?random=5",
      hint: "land plot ocean",
      price: "18 500 000 FCFA",
      area: 180,
      isNew: false,
      description: "Terrain de 180m² à Yenne, une zone en pleine expansion offrant un fort potentiel de plus-value. Idéal pour un investissement à long terme ou pour construire une résidence familiale dans un environnement calme et proche de la nature. La proximité de l'océan en fait un emplacement de choix.",
      features: ["Fort potentiel d'investissement", "Proximité de la mer", "Environnement paisible"],
    },
    {
      id: "ngor-01",
      title: "Studio moderne à Ngor",
      type: "Appartement",
      image: "https://picsum.photos/1200/800?random=6",
      hint: "modern studio ngor",
      price: "Nous consulter",
      bedrooms: 1,
      bathrooms: 1,
      area: 50,
      isNew: true,
      description: "Charmant studio neuf et moderne dans le quartier animé de Ngor. Parfait pour un célibataire ou un jeune couple. Il est meublé avec goût et dispose d'un coin cuisine fonctionnel et d'un balcon. L'immeuble est récent, sécurisé et proche de la plage, des restaurants et des commerces.",
      features: ["Quartier dynamique", "Entièrement meublé", "Proche de la plage de Ngor"],
    },
    {
      id: "vue-mer-01",
      title: "Terrain avec vue sur mer",
      type: "Terrain",
      image: "https://picsum.photos/1200/800?random=7",
      hint: "land sea view",
      price: "35 000 000 FCFA",
      area: 250,
      isNew: false,
      description: "Opportunité rare : terrain de 250m² offrant une vue imprenable sur l'océan. Situé sur la corniche, c'est l'endroit idéal pour construire une villa de prestige ou un petit immeuble de rapport. Le cadre est exceptionnel et très recherché.",
      features: ["Vue mer panoramique", "Emplacement premium", "Titre foncier sécurisé"],
    },
    {
      id: "ouakam-01",
      title: "Maison familiale à Ouakam",
      type: "Maison",
      image: "https://picsum.photos/1200/800?random=8",
      hint: "family house ouakam",
      price: "Nous consulter",
      bedrooms: 3,
      bathrooms: 2,
      area: 180,
      isNew: false,
      description: "Agréable maison familiale de 3 chambres située dans le quartier résidentiel de Ouakam. Elle dispose d'un petit jardin, d'un salon spacieux et d'une cuisine pratique. Le quartier est calme, familial et bien desservi par les transports. Proche du Monument de la Renaissance Africaine.",
      features: ["Quartier résidentiel calme", "Jardin privé", "Bon état général"],
    },
    {
      id: "mermoz-01",
      title: "Duplex de standing à Mermoz",
      type: "Maison",
      image: "https://picsum.photos/1200/800?random=9",
      hint: "duplex house mermoz",
      price: "Nous consulter",
      bedrooms: 5,
      bathrooms: 4,
      area: 300,
      isNew: true,
      description: "Luxueux duplex de 300m² dans le quartier chic de Mermoz. Offrant de grands volumes et des prestations de haute qualité, il se compose de 5 chambres, d'un double séjour, et d'une grande terrasse sur le toit avec vue. Idéal pour une grande famille cherchant le confort et le prestige.",
      features: ["Finitions de luxe", "Grande terrasse (rooftop)", "Quartier sécurisé et prisé"],
    },
    {
      id: "sindia-01",
      title: "Terrain commercial à Sindia",
      type: "Terrain",
      image: "https://picsum.photos/1200/800?random=10",
      hint: "commercial land",
      price: "45 000 000 FCFA",
      area: 500,
      isNew: false,
      description: "Grand terrain de 500m² à usage commercial, situé sur un axe stratégique à Sindia, près de l'aéroport AIBD et de la zone industrielle. Idéal pour un projet d'entrepôt, de commerce ou de bureaux. Excellente visibilité et accessibilité.",
      features: ["Emplacement stratégique", "Forte visibilité", "Idéal pour projet commercial"],
    },
    {
      id: "almadies-01",
      title: "Appartement F2 aux Almadies",
      type: "Appartement",
      image: "https://picsum.photos/1200/800?random=11",
      hint: "apartment almadies",
      price: "Nous consulter",
      bedrooms: 1,
      bathrooms: 1,
      area: 80,
      isNew: false,
      description: "Bel appartement d'une chambre dans le quartier huppé des Almadies. Spacieux et bien agencé, il est parfait pour un investissement locatif ou un pied-à-terre à Dakar. La résidence est de haut standing, avec piscine, salle de sport et gardiennage.",
      features: ["Quartier des ambassades", "Résidence de haut standing", "Piscine et salle de sport"],
    },
    {
      id: "medina-01",
      title: "Maison à rénover à la Médina",
      type: "Maison",
      image: "https://picsum.photos/1200/800?random=12",
      hint: "house renovate medina",
      price: "Nous consulter",
      bedrooms: 3,
      bathrooms: 1,
      area: 120,
      isNew: false,
      description: "Maison avec un fort potentiel de rénovation au cœur du quartier historique et populaire de la Médina. Une excellente opportunité de créer un logement à votre goût ou un projet d'investissement type auberge ou location. La structure est saine et offre de belles possibilités d'aménagement.",
      features: ["Fort potentiel de rénovation", "Au cœur d'un quartier authentique", "Bon investissement locatif"],
    }
  ];
  
  export type Property = (typeof properties_data)[0];